config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'

  match '/signup', to: 'users#new'
  match '/home', to: 'static_pages#home'
  match '/contact', to: 'static_pages#contact'
  match '/about', to: 'static_pages#about'
  match '/help', to: 'static_pages#help'

  root to: 'static_pages#home'
end

app/models/user.rb
# == Schema Information
# Schema version: 20120304150254
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime        not null
#  updated_at         :datetime        not null
#  encrypted_password :string(255)
#  password_digest    :string(255)
#  remember_token     :string(255)
#  admin              :boolean         default(FALSE)
#
# Indexes
#
#  index_users_on_remember_token  (remember_token)
#  index_users_on_email           (email) UNIQUE
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password

  before_save :create_remember_token

  validates :name,  presence: true,
                    length: { maximum: 50 }

  valid_email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true,
                    format: { with: valid_email_regex },
                    uniqueness: {case_sensitive: false}
  validates :password, length: { within: 6..40 }

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def help
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination' # Not quite right!
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
    @title='About Us'
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find params[:id]
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to(@user)
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end

  private
    def signed_in_user
      unless signed_in?
        store_location
        redirect_to(signin_path, notice: "Please sign in")
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to root_path unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

  def logo
    image_tag "logo.png", alt: base_title, class: "round"
  end

private
  def base_title
    "KarachiCrime"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    current_user = user
  end

  def sign_out
    cookies.delete(:remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end

  def store_location
    session[:return_to] = request.fullpath
  end

  private
    def user_from_remember_token
      remember_token = cookies[:remember_token]
      User.find_by_remember_token(remember_token) unless remember_token.nil?
    end

    def clear_return_to
      session.delete(:return_to)
    end
end

app/helpers/users_helper.rb
module UsersHelper
 def gravatar_for(user, options = { size: 50 })
   gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
   size = options[:size]
   gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png&s=#{size}"
   image_tag(gravatar_url, alt: user.name, class: "gravatar")
 end
end

app/views/layouts/_footer.html.haml
%footer
  %nav.round
    %ul
      %li= link_to "About", about_path
      %li= link_to "Contact", contact_path
      %li= link_to "News", '#'
      %li= link_to "KC", '#'

app/views/layouts/_header.html.haml
%header
  %nav.round
    %ul
      %li= link_to "Home", root_path
      -if signed_in?
        %li= link_to "Users", users_path
        %li= link_to "Profile", current_user
        %li= link_to "Settings", edit_user_path(current_user)
      %li= link_to "Help", help_path
      -if signed_in?
        %li= link_to "Sign out", signout_path, method: :delete
      -else
        %li= link_to "Sign in", signin_path
= link_to logo, root_path

app/views/layouts/_stylesheets.html.haml
/[if lt IE 9]
  %script{:src => "http://html5shiv.googlecode.com/svn/trunk/html5.js"}

= stylesheet_link_tag 'blueprint/screen', media: 'screen'
= stylesheet_link_tag 'blueprint/print', media: 'print'
/[if lt IE 8]
  = stylesheet_link_tag 'blueprint/ie' 
= stylesheet_link_tag 'application', media: 'all'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    = render 'layouts/stylesheets'
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container
      = render 'layouts/header'
      %section.round
        -flash.each do |key, value|
          = content_tag(:div, value, class: "flash #{key}")
        = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?

app/views/shared/_error_messages.html.haml
-if @user.errors.any?
  #error_explanation
    %h2
      = pluralize(@user.errors.count, "error")
      prohibited this user from being saved:
    %p
      There were problems with the following fields:
    %ul
      -@user.errors.full_messages.each do |msg|
        %li= msg

app/views/static_pages/about.html.haml
- provide(:title, 'About')

%h1 About Us
%p
  KarachiCrime is a project to allow citizens of Karachi to report crime.

app/views/static_pages/contact.html.haml
- provide(:title, 'Contact')

%h1 Contact
%p
  Contact KarachiCrime about the project at the
  %a karachicrime.org/feedback
  page

app/views/static_pages/help.html.haml
- provide(:title, 'Help')

%h1 Help

%p
  Get help on Ruby on Rails Tutorial at the

app/views/static_pages/home.html.haml
- provide(:title, 'Home')

%h1 KarachiCrime
%p
  This is the home page for the
  %a{href: "http://karachicrime.org"} KarachiCrime
  the crowd sourced application.

%p
  = link_to "Sign up now!", signup_path, :class => "signup_button round"

%p
  Nullam id dolor id nibh ultricies vehicula ut id elit. Vestibulum id ligula porta felis euismod semper.
  Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Morbi leo risus, porta ac
  consectetur ac, vestibulum at eros.

%p
  Nullam quis risus eget urna mollis ornare vel eu leo. Donec id elit non mi porta gravida at eget metus.
  Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Morbi leo risus, porta ac consectetur
  ac, vestibulum at eros. Etiam porta sem malesuada magna mollis euismod.

%p
  Maecenas sed diam eget risus varius blandit sit amet non magna. Duis mollis, est non commodo luctus, nisi
  erat porttitor ligula, eget lacinia odio sem nec elit. Fusce dapibus, tellus ac cursus commodo, tortor mauris
  condimentum nibh, ut fermentum massa justo sit amet risus. Curabitur blandit tempus porttitor. Sed posuere
  consectetur est at lobortis.

app/views/users/_user.html.haml
%li
  = gravatar_for(user, size: 30)
  = link_to user.name, user
  - if current_user.admin? && !current_user?(user)
    |
    = link_to "delete", user, method: :delete, confirm: "You sure?"

app/views/users/edit.html.haml
- provide :title, "Edit user"

%h1 Edit user

= form_for(@user) do  |f|
  = render 'shared/error_messages'
  .field
    = f.label :name
    %br
    = f.text_field :name
  .field
    = f.label :email
    %br
    = f.text_field :email
  .field
    = f.label :password
    %br
    = f.text_field :password
  .field
    = f.label :password_confirmation, "Confirmation"
    %br
    = f.text_field :password_confirmation
  .actions
    = f.submit "Update"
%div
  = gravatar_for(@user)
  %a{href: "http://gravatar.com/emails"} change

app/views/users/index.html.haml
- provide :title, 'All users'

%h1 All users

= will_paginate

%ul.users
  = render @users

= will_paginate

app/views/users/new.html.haml
-provide(:title, 'Sign up') 
%h1 Sign up

= form_for @user do |f|
  = render 'shared/error_messages'
  .field
    =f.label :name
    %br
    =f.text_field :name
  .field
    =f.label :email
    %br
    =f.text_field :email
  .field
    =f.label :password
    %br
    =f.password_field :password
  .field
    =f.label :password_confirmation, "Confirmation"
    %br
    =f.password_field :password_confirmation
  .actions
    = f.submit "Sign up"

app/views/users/show.html.haml
- provide :title, @user.name

%table.profile
  %tr
    %td.main
      %h1
        = gravatar_for @user
        = @user.name
    %td.sidebar.round
      %strong Name
      = @user.name
      %br
      %strong URL
      = link_to user_path(@user), @user